"use client";

import { useEffect, useState } from "react";
import { ArrowLeft, ArrowUpRight, RotateCw, ShoppingBag, X } from "lucide-react";
import { Dialog, DialogClose, DialogContent, DialogDescription, DialogTitle } from "@/components/ui/dialog";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { ClubContent, Fit, imageFrames, Product } from "@/lib/club";

const whatsappUrl = (product: Pick<Product, "name" | "label">) => `https://wa.me/5516999936420?text=${encodeURIComponent(`Olá! Tenho interesse na peça "${product.name}" (${product.label}). Pode me enviar tamanhos, valores e disponibilidade?`)}`;
function Instagram({ size = 20 }: { size?: number }) { return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5" /><circle cx="12" cy="12" r="4" /><circle cx="17.5" cy="6.5" r=".8" fill="currentColor" stroke="none" /></svg>; }

function Shirt({ product, fit, side = "back", priority = false }: { product: Product; fit: Fit; side?: "back" | "front"; priority?: boolean }) {
  if (side === "front") {
    const frontKey = `front-${fit}`;
    const frontFrame = imageFrames[frontKey];
    return <div className="shirt-crop" style={{ aspectRatio: frontFrame ? `${frontFrame.width} / ${frontFrame.bottom - frontFrame.top}` : "1 / 1" }}><img src={`/images/${frontKey}.png`} alt={`${product.name}, frente, ${fit}`} loading={priority ? "eager" : "lazy"} /></div>;
  }
  if (product.photo) return <div className="shirt-crop custom-shirt-crop"><img src={product.photo} alt={`${product.name}, ${product.label}`} loading={priority ? "eager" : "lazy"} /></div>;
  const key = `${product.id}-${fit}`;
  const frame = imageFrames[key] || imageFrames[`${product.id}-oversized`] || { width: 700, height: 700, top: 0, bottom: 700 };
  return <div className="shirt-crop" style={{ aspectRatio: `${frame.width} / ${frame.bottom - frame.top}` }}><img src={`/images/${key}.png`} alt={`${product.name}, ${product.label}`} loading={priority ? "eager" : "lazy"} width={frame.width} height={frame.height} style={{ top: `${-100 * frame.top / (frame.bottom - frame.top)}%` }} /></div>;
}

function ProductDetails({ product, fit, onClose }: { product: Product | null; fit: Fit; onClose: () => void }) {
  const [selectedFit, setSelectedFit] = useState<Fit>(fit);
  const [side, setSide] = useState<"back" | "front">("back");
  useEffect(() => { setSelectedFit(fit); setSide("back"); }, [product, fit]);
  return <Dialog open={!!product} onOpenChange={open => { if (!open) onClose(); }}><DialogContent className="product-dialog" showCloseButton={false}><DialogClose className="dialog-close icon-button" aria-label="Fechar detalhes"><X size={22} /></DialogClose>{product && <><div className="detail-visual"><span className="photo-counter mono">{side === "back" ? "01 / COSTAS" : "02 / FRENTE"}</span><Shirt product={product} fit={selectedFit} side={side} priority /><button className="flip-button" onClick={() => setSide(side === "back" ? "front" : "back")}><RotateCw size={16} />Ver {side === "back" ? "frente" : "costas"}</button></div><div className="detail-info"><span className="eyebrow">MIDNIGH7 WEAR / {product.type.toUpperCase()} / EDIÇÃO {product.edition}</span><DialogTitle>{product.name}</DialogTitle><DialogDescription>Uma paixão que também se veste. {product.label}. Consulte os tamanhos e condições do lote pelo WhatsApp.</DialogDescription><span className="field-title">MODELAGEM</span><Tabs value={selectedFit} onValueChange={value => setSelectedFit(value as Fit)}><TabsList className="fit-tabs"><TabsTrigger value="oversized">Oversized</TabsTrigger><TabsTrigger value="babylook">Babylook</TabsTrigger></TabsList><TabsContent value="oversized"><p className="fit-description">Modelagem masculina oversized.</p></TabsContent><TabsContent value="babylook"><p className="fit-description">Modelagem feminina babylook.</p></TabsContent></Tabs><div className="detail-note"><span className="gold-label">VENDA POR LOTE</span><p>As camisetas são produzidas em lotes. Fale com a gente para reservar a sua.</p></div><a className="button button-gold" href={whatsappUrl(product)} target="_blank" rel="noopener noreferrer"><ShoppingBag size={19} />Pedir pelo WhatsApp<ArrowUpRight size={19} /></a><p className="mockup-note">Imagens de referência das estampas.</p></div></>}</DialogContent></Dialog>;
}

export default function RoupasCatalog({ content }: { content: ClubContent }) {
  const [fit, setFit] = useState<Fit>("oversized");
  const [selectedProduct, setSelectedProduct] = useState<Product | null>(null);
  const contactProduct = content.products[0] || { name: "uma peça", label: "catálogo" };
  return <><header className="header"><div className="nav-wrap"><a className="brand" href="/" aria-label="Voltar para o Midnigh7 Club"><img src="/images/logo.png" alt="Midnigh7 Club" width={220} height={50} /></a><a className="text-link" href="/"><ArrowLeft size={16} />Voltar ao clube</a><a className="nav-instagram" href={content.instagram} target="_blank" rel="noopener noreferrer"><Instagram size={18} />Instagram<ArrowUpRight size={15} /></a></div></header><main className="clothing-marketplace"><div className="container"><div className="marketplace-hero"><div><span className="eyebrow"><span className="gold-line" />MIDNIGH7 WEAR / LOJA DO CLUBE</span><h1>Vista essa <span>paixão.</span></h1><p>Peças feitas para quem vive a cultura automotiva. Escolha sua estampa e fale com a gente para entrar no próximo lote.</p></div><div className="marketplace-badge"><ShoppingBag size={25} /><span>Venda atual<br /><strong>por lote</strong></span></div></div><div className="marketplace-toolbar"><div><span className="mono">CATÁLOGO / {String(content.products.length).padStart(2, "0")} PEÇAS</span><p>Modelagens e estampas do momento.</p></div><Tabs value={fit} onValueChange={value => setFit(value as Fit)}><TabsList className="fit-tabs" aria-label="Filtrar por modelagem"><TabsTrigger value="oversized">Oversized</TabsTrigger><TabsTrigger value="babylook">Babylook</TabsTrigger></TabsList></Tabs></div><div className="marketplace-grid">{content.products.map((product, index) => <button className="product-card marketplace-card" key={product.id} onClick={() => setSelectedProduct(product)} aria-label={`Ver ${product.name}, ${product.label}`}><div className="product-image"><div className="product-tags"><span className="mono">ED. {product.edition}</span><span className="mono">{product.type.toUpperCase()}</span></div><Shirt product={product} fit={fit} priority={index < 2} /><span className="view-product">Ver detalhes<ArrowUpRight size={17} /></span></div><div className="product-caption"><div><span className="mono product-edition">{product.label}</span><h3>{product.name}</h3><p>{product.cuts.join(" · ")}</p></div><span className="product-open"><ArrowUpRight size={21} /></span></div></button>)}</div><div className="marketplace-contact"><div><span className="eyebrow"><span className="gold-line" />ATENDIMENTO</span><h2>Quer garantir a sua?</h2><p>Chame no WhatsApp e consulte tamanhos, valores e disponibilidade do próximo lote.</p></div><a className="button button-gold" href={whatsappUrl(contactProduct)} target="_blank" rel="noopener noreferrer"><ShoppingBag size={19} />Falar no WhatsApp<ArrowUpRight size={19} /></a></div></div></main><ProductDetails product={selectedProduct} fit={fit} onClose={() => setSelectedProduct(null)} /></>;
}
