"use client";
import { useEffect, useRef, useState } from "react";
import { ArrowDown, ArrowUpRight, Check, Menu, X } from "lucide-react";
import { Sheet, SheetClose, SheetContent, SheetDescription, SheetTitle, SheetTrigger } from "@/components/ui/sheet";
import { ClubContent, instagramUsername, Member } from "@/lib/club";
const links = [{ id: "o-grupo", title: "O grupo", href: "#o-grupo" }, { id: "membros", title: "Referências", href: "#membros" }, { id: "participar", title: "Como participar", href: "#participar" }, { id: "roupas", title: "Roupas", href: "/roupas" }];
function Instagram({ size = 20 }: { size?: number }) { return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5" /><circle cx="12" cy="12" r="4" /><circle cx="17.5" cy="6.5" r=".8" fill="currentColor" stroke="none" /></svg>; }

function MemberCard({ member }: { member: Member }) {
  const [photoFailed, setPhotoFailed] = useState(false);
  const number = String(member.id).padStart(2, "0");
  const inner = <><div className="member-top"><span className="mono">{number} / 07</span>{member.instagram && <ArrowUpRight size={17} />}</div><div className="member-avatar">{member.photo && !photoFailed ? <img loading="lazy" src={member.photo} alt={member.name || member.username} onError={() => setPhotoFailed(true)} /> : <span>{number}</span>}</div><h3>{member.name || (member.username ? `@${member.username}` : `Referência ${number}`)}</h3><p className="member-handle">{member.username ? `@${member.username}` : "Perfil em breve"}</p>{member.bio && <p className="member-bio">{member.bio}</p>}<span className="member-role">REFERÊNCIA</span></>;
  return member.instagram ? <a className="member-card" href={member.instagram} target="_blank" rel="noopener noreferrer" aria-label={`Instagram de ${member.name || member.username}`}>{inner}</a> : <article className="member-card member-empty">{inner}</article>;
}
export default function ClubSite({ content }: { content: ClubContent }) {
  const [activeSection, setActiveSection] = useState("");
  const [menuOpen, setMenuOpen] = useState(false);
  const menuTarget = useRef<string | null>(null);
  const handle = instagramUsername(content.instagram) || "midnigh7.club";
  useEffect(() => { const observer = new IntersectionObserver(entries => entries.forEach(entry => { if (entry.isIntersecting) setActiveSection(entry.target.id); }), { rootMargin: "-20% 0px -55% 0px" }); document.querySelectorAll("section[id]").forEach(el => observer.observe(el)); return () => observer.disconnect(); }, []);
  return <><a className="skip-link" href="#conteudo">Pular para o conteúdo</a><header className="header"><div className="nav-wrap"><a className="brand" href="#inicio" aria-label="Midnigh7 Club, início"><img src="/images/logo.png" alt="Midnigh7 Club" width={220} height={50} /></a><nav className="desktop-nav" aria-label="Navegação principal">{links.map(link => <a key={link.id} href={link.href} className={`${activeSection === link.id ? "active " : ""}${link.id === "roupas" ? "nav-clothing-link" : ""}`}>{link.title}</a>)}</nav><a className="nav-instagram" href={content.instagram} target="_blank" rel="noopener noreferrer"><Instagram size={18} /><span>@{handle}</span><ArrowUpRight size={15} /></a><Sheet open={menuOpen} onOpenChange={setMenuOpen}><SheetTrigger asChild><button className="menu-toggle icon-button" aria-label="Abrir menu"><Menu size={24} /></button></SheetTrigger><SheetContent className="mobile-menu" showCloseButton={false} onCloseAutoFocus={event => { if (menuTarget.current) { event.preventDefault(); const target = menuTarget.current; menuTarget.current = null; window.history.replaceState(null, "", `#${target}`); requestAnimationFrame(() => document.getElementById(target)?.scrollIntoView({ behavior: window.matchMedia("(prefers-reduced-motion: reduce)").matches ? "instant" : "smooth", block: "start" })); } }}><div className="menu-heading"><SheetTitle><img src="/images/logo.png" width={190} height={43} alt="Midnigh7 Club" /></SheetTitle><SheetClose className="icon-button" aria-label="Fechar menu"><X /></SheetClose></div><SheetDescription className="sr-only">Navegue pelas seções do clube.</SheetDescription><nav aria-label="Navegação móvel">{links.map((link, i) => <a key={link.id} className={link.id === "roupas" ? "mobile-clothing-link" : ""} href={link.href} onClick={event => { if (link.href.startsWith("/")) { setMenuOpen(false); return; } event.preventDefault(); menuTarget.current = link.id; setMenuOpen(false); }}><span className="mono">0{i + 1}</span>{link.title}<ArrowUpRight /></a>)}</nav><a className="button button-gold" href={content.instagram} target="_blank" rel="noopener noreferrer"><Instagram size={18} />Nosso Instagram</a><span className="menu-footer mono">DIFERENTES PROJETOS. A MESMA PAIXÃO.</span></SheetContent></Sheet></div></header>
  <main id="conteudo"><section id="inicio" className="hero"><img className="hero-image" src="/images/tokyo-night.png" alt="Cupê japonês em uma rua noturna de Tóquio, com reflexos dourados no asfalto" width={1918} height={820} fetchPriority="high" /><div className="hero-shade" /><div className="hero-content container"><p className="eyebrow"><span className="gold-line" />CULTURA AUTOMOTIVA. CONEXÕES REAIS.</p><h1>MOVIDOS<br />PELA MESMA<br /><span>PAIXÃO.</span></h1><p className="hero-copy">Diferentes carros. Diferentes histórias.<br />Um só lugar para quem sente o mesmo.</p><div className="hero-actions"><a className="button button-gold" href="#participar">Faça parte do clube<ArrowUpRight size={20} /></a><a className="text-link" href="#o-grupo">Conheça o Midnigh7<ArrowDown size={17} /></a></div></div><div className="hero-side mono" aria-hidden="true">TOKYO INSPIRED<span />PASSION DRIVEN</div><div className="hero-bottom container"><span className="mono"><span className="tiny-gold">07</span> / DIFERENTES PROJETOS. A MESMA ESSÊNCIA.</span><a href="#o-grupo" className="scroll-link" aria-label="Conhecer o grupo"><span className="mono">EXPLORE</span><ArrowDown size={17} /></a></div></section>
  <div className="culture-strip" aria-hidden="true"><div><span>ALL CARS. ONE PASSION.</span><span className="strip-star">✦</span><span>RESPEITO A CADA PROJETO.</span><span className="strip-star">✦</span><span>MIDNIGH7 CLUB</span><span className="strip-star">✦</span><span>ALL CARS. ONE PASSION.</span><span className="strip-star">✦</span><span>RESPEITO A CADA PROJETO.</span></div></div>
  <section id="o-grupo" className="about-section section container"><div className="section-label"><span className="mono">01 / O GRUPO</span><span className="section-rule" /></div><div className="about-grid"><div><h2>MAIS QUE CARROS.<br /><span className="text-gold">QUEM ESTÁ<br />POR TRÁS DELES.</span></h2><div className="about-stamp"><span className="stamp-seven">7</span><div className="mono">UMA PAIXÃO EM COMUM.<br />NENHUM PROJETO IGUAL.</div></div></div><div className="about-copy">{content.story.split(/\n\s*\n/).filter(Boolean).map((p, i) => <p key={i}>{p}</p>)}<div className="values-row"><span><Check size={15} />Todas as marcas</span><span><Check size={15} />Respeito sempre</span><span><Check size={15} />Paixão de verdade</span></div></div></div></section>
  <section id="membros" className="members-section section container"><div className="section-label"><span className="mono">03 / OS SETE</span><span className="section-rule" /></div><div className="section-heading"><div><h2>SETE PESSOAS.<br /><span className="text-gold">UMA DIREÇÃO.</span></h2></div><p>A equipe que faz o<br />Midnigh7 Club acontecer.</p></div><div className="members-grid">{content.members.map(member => <MemberCard key={`${member.id}-${member.photo}`} member={member} />)}</div></section>
  <section id="participar" className="join-section"><div className="join-watermark" aria-hidden="true">7</div><div className="container join-inner"><div className="section-label"><span className="mono">04 / COMO PARTICIPAR</span><span className="section-rule" /></div><div className="join-grid"><div><p className="eyebrow">TEM PAIXÃO POR CARROS?</p><h2>O PRÓXIMO<br />CAPÍTULO PODE<br />SER <span className="text-gold">COM VOCÊ.</span></h2></div><div className="join-copy"><p>A marca é detalhe.<br /><strong>A paixão é o que importa.</strong></p><p>Entre em contato pela nossa página no Instagram para consultar a disponibilidade de vagas no grupo e saber como participar.</p><a className="button button-gold" href={content.instagram} target="_blank" rel="noopener noreferrer"><Instagram size={20} />Conversar no Instagram<ArrowUpRight size={20} /></a><span className="join-handle">@{handle}</span><div className="join-note">A entrada no grupo está sujeita à disponibilidade de vagas.</div></div></div></div></section></main>
  <footer className="footer container"><div className="footer-top"><a href="#inicio" className="brand"><img src="/images/logo.png" alt="Midnigh7 Club" width={220} height={50} /></a><p>Diferentes projetos. A mesma paixão.</p><a className="footer-social" href={content.instagram} target="_blank" rel="noopener noreferrer" aria-label="Instagram do Midnigh7 Club"><Instagram size={21} /><ArrowUpRight size={16} /></a></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Midnigh7 Club</span><span className="footer-independent">Clube independente. Inspirado na cultura automotiva japonesa.</span><a href="/admin">Painel do clube</a></div></footer></>;
}
